# https://vuepress.github.io/zh/guide/deployment.html#github-pages
name: sync

on:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        with:
          source-repo: git@github.com:ModyQyW/resume.git
          destination-repo: git@gitee.com:ModyQyW/resume.git
        env:
          SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
      - name: Deploy to Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: ModyQyW
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: ModyQyW/resume
          branch: main
